travis:
  secure:
    BINSTAR_TOKEN: R4bt4oBPGYOtGShyM5m6kzRYMKAUiRoC2+ykOpuY1nNrz0JOoGfdRkXdAomSOVvJf/501fxEEmlPVfm8yIhf88OQqXyqjpdP9k95cpaZqSHXZ/8ySjnJiuhfzB0Pm2rJ/Lm1+44PaP7X7GAXrsk9EjpwF/YuFrbBNrHLzJmOOeRA8feQ6TtgmFvCk9r9qqoQhMkdM9FdsM3QCgawxNWPYW0hcK0Om3OUpDFfclZQrkJQ1Pz/KD7KQER3I5vOx6x8gWBsH8pz+2crZeAMQoMZOSNnhqCErq+U1SGIGffe3tkgi1nEBus9ncio6g8ysIzQ2MXMk0kYY1OjG96aXlD4IG3pfnrWQh7CjW0ZUvs5fm3xCXJ4fbcpW+GfXOZHhfrnN9iPuhhLGStDpsI/L4SzNM6/Qsz1Esx0jq6vhGlinNve/aDG0hMpuxfERdqYudiaYmMUFRAMXc8GfcIgCInhwIdFUil5MemoUOzNHfn8ixs/45r1yHpPYla+X96JTRualMPSktaje+6ZL/hrZxnfiOjFGtxLvnFOti740Ts3zLtfbu1qmYzMF6qCtDVM0R++A39Jn1ckgQN5HYvp4jGxXUm6UoyIxBTSmXGDgMTTPWoxhQsN0Xuln4uxGy3rE0LQv61UtfOQGUi5l6k0LEthajahlkgYEnBGNT2mPcLqpfE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
