travis:
  secure:
    BINSTAR_TOKEN: Cyz931iQ2OB/Ht9SmfwqIUrJ3Dt9lnGZuESboUleXTDGcbTG37ndcvBoHQemN0l0V807gciq8T4fy/a7ss8nUh/h0NiF14qnGY86XM8+O4zf80Rstzd0ZY1lVsHMAL3kr7+5LnzfQLuz9Z9wJM3UrINFPAP08TkeI+1jkdO3tRoSHtw7IbM+51GThv+AQYeNsmn2x+wgQmqzy8emolM7r4ih1GNsWquQ/pA+5HVNmQGxYm0ASQe1OjuezYm0aQ8kynQrkroYP09louCkzvNV68jcE3lN7YAYFMNT44qJGr7E0UOuXnf4aT6NGmyXFKUEZZdHU7FfVV+4drXZQKB+xAjg0/hW72LtrN5msCzkfwjDEBLL7Q4WvmZp2gOd89B+M4PkfEJ5AJVDcLkXj2MP1O2OzJnERuQoNi6tuKXD9HO9Sf4cP5/9/NUAyn3ISecHbbF6qnClq4hmM34ANNap5V1bhMoNzfz79aCeCx/2kRpP2NdqraCQ2NpIlAIfLv22pDfYafeN3j/8tKoy/TiLmkol7KUlC/a3IecgvJ1UMa+f2JUfR3uPUjGbTxSRehgEt3yzAnBzxszz0yRdKkGIaKoyWNe8qj+lL/ePSD12D8cQsFseKKnTEQqhBjOHrSsRhYZdtr/cmYUEATx8cvIh/cjxEBC/X+BGZ75ja6VFnLI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
