travis:
  secure:
    BINSTAR_TOKEN: DciN7XqC+1oKKOje8RQtjvQ3lN1hfgBrgVWJcS+32NbWiCcGjUPMx8oKwcC7+TJK90klfjOzd+B3pzhyMx9Ab8C7QAPK6M4a7lINKCZqfJ9rNu5lkg88UT6+f6smBwc/4dCb+roWBzqRFGin5ksowxGY88P5ekbusJvsnOxq6h9OUXvwCIrb5DOcQNv5cBl8ZNSHTAehbu+TlxpcMf8jCFyloc3CCnMDjv5lDavoWcqxBpyLmS1HZNXpgiQ/KPyrHBMY5b/AIlSdzNFKq9aHrBpZJOF7aaNz+cNFCJ2wTY8lxOeeo5kuqoPi1EfA2zCb8x+eZMJzbZuDXC2ifRaIrwIxjCjKRzDCei47xrtiZx62fWFCHztba9MPSkHQz0V6uUGvQyJ358Yv6o3dn3BH6krC8WgfWGazeUGiA291lCKsy5bv+DLLEVwcYqi+eBTgVE/sSyG+KtHQPf/D7jGTQRkyjQOTRP9uWwB0OoGqoLouMn+1hFmeHUVtEKxzLlW0btjDD6L6U74yKGfS0nJ0bVjiTWdWB+Aj4KRH3JkujOCAJ0TA4SB87/varfIkDFaT2b0eGubR6s1tR9gMkREc+O44/KS3i29vMMqnxXGIyx7XTZBSwuYmk+1lym+728lRgftr1nbYNnzp7Rz3BJ8ISppRpA9+UW3ZVLYPLHsXiLk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
